### ISSUE TITLE
Error in build for IOS

### ISSUE THREAD

**Issue by kelvgraf** [frw/react-native-ssl-public-key-pinning#140]
Hello!
I'm using react-native-ssl-public-key-pinning, but when building the app I'm receiving the following error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTHTTPRequestHandler", referenced from:
      __OBJC_$_CATEGORY_RCTHTTPRequestHandler_$_SslPublicKeyPinning in SslPublicKeyPinning.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _OBJC_CLASS_$_RCTHTTPRequestHandler
```

**Comment by frw** [comment]
Hey @kelvgraf,

What version of react-native are you using?
Have you run `pod install` in the `ios` directory?

**Comment by kelvgraf** [comment]
Thanks for responding <3

I'm using version: 0.68.2

Yes, I ran pod install and I'm using use_frameworks!

**Comment by frw** [comment]
Hey @kelvgraf

This issue should be fixed in v1.1.3
Let me know if you're still facing issues!

**Comment by NG-Joseph** [comment]
@frw Doing the lord's work!

**Comment by kelvgraf** [comment]
Bro thank you very much it worked @frw  <3 <3 <3

**Comment by frw** [comment]
Great to hear it's working! Closing this issue.
