### ISSUE TITLE
IOS17 support Trust Kit Crash (iphone15 physical)

### ISSUE THREAD

**Issue by LeoAnt02** [frw/react-native-ssl-public-key-pinning#147]
Currently the ssl-pining cause a crash on new iPhones 15 Pro physical devices 
I tried on simulator iphone 15 and Iphone 15 Pro- ios 17.0.0 - and there is no issues

This is breaking production devices also

Target Device : 
**Iphone 15 Pro  (Physical)
IOS v17.0.2**
**react-native-ssl-public-key-pinning v^1.1.3**
**Xcode 15**

There is no error in console, will have to debug further and edit this post 
But this is where Xcode crash in screenshot below

**Issue seems to come from TrustKit need a little update with version 17.0.2 (iphone15)**

<img width="1895" alt="Screenshot 2023-09-27 at 8 55 41 PM" src="https://github.com/frw/react-native-ssl-public-key-pinning/assets/21208398/8361b96a-8a17-49d0-87b0-0a792c6e39c9">

_Something I've noticed that may cause an issue, is that iphone15 Pro (physical), is read as an Iphone16 in singature binaries, I believe this is a mistake from apple, not sure if this affect TrustKit or SSL pining but worth to mention it_

**Comment by frw** [comment]
Hey @LeoAnt02,

Appreciate the bug report. Could you also file this issue in the [TrustKit repo](https://github.com/datatheorem/TrustKit) ? It seems like the issue is on the TrustKit side and will need to be resolved there.

Will keep this issue open for tracking.

Thanks!

**Comment by LeoAnt02** [comment]
Hey @frw 

Thanks for the response, just opened a issue on their repo too 

https://github.com/datatheorem/TrustKit/issues/314 

What version TrustKit are we using right now ? just for info

**Comment by frw** [comment]
@LeoAnt02 

[We don't pin to a specific TrustKit version](https://github.com/frw/react-native-ssl-public-key-pinning/blob/main/react-native-ssl-public-key-pinning.podspec#L37). You can see the version that you're using in your Podfile.lock
You could also try upgrading TrustKit to the latest version by doing `pod update` .

**Comment by LeoAnt02** [comment]
Thanks for the response, I've successfully solved the issue  b Updating spec repo `cocoapods` on ios for TrustKit 3.0.3 (was using 3.0.2)

```
pod repo update
pod install
```

Then trustkit was updated to 3.0.3 and everything works now
