### ISSUE TITLE
Is there any way to see if the certificate is actually pinned?

### ISSUE THREAD

**Issue by pdlm95** [frw/react-native-ssl-public-key-pinning#19]
Hi! I am trying to pin a client certificate with axios and I was wondering if the key should be reflected somehow in the requests? The implementation is the same as stated in the docs.

Even isSslPinningAvailable returns true but I can't see if something is really happening after pinning.

Some help will be appreciated!

**Comment by frw** [comment]
@pdlm95

An easy way to test that the pinning is happening is by providing the wrong public key hashes to `initializeSslPinning`, e.g.
```
await initializeSslPinning({
  'google.com': {
    includeSubdomains: true,
    publicKeyHashes: [
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
    ],
  },
});

// ...

// This request should fail with an error
const response = await fetch('google.com');
```

If the request fails, you'll know you've set it up correctly if you switch back to the correct public key hashes while leaving everything else the same
