### ISSUE TITLE
build failed when enable new arch with react-native@0.73

### ISSUE THREAD

**Issue by iwater** [frw/react-native-ssl-public-key-pinning#278]
build failed when enable new arch with react-native@0.73

fatal error: 'RNSslPublicKeyPinningSpec.h' file not found
#import "RNSslPublicKeyPinningSpec.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by frw** [comment]
@iwater

Thanks for bringing up this issue. This should be fixed in v1.2.0. Let me know if you come across any other issues with it!
