### ISSUE TITLE
How to disable network inspector in react-native-cli

### ISSUE THREAD

**Issue by gkasireddy202** [frw/react-native-ssl-public-key-pinning#351]
I am using the react-native version:0.68.7.
How to disable the network inspector on release and debug mode.

**Comment by frw** [comment]
Are you using Expo and `expo-dev-client`? If you're not, there is no need to disable Network Inspector.

**Comment by gkasireddy202** [comment]
@frw  - Thanks for your reply.
I am using the react-native-ssl-public-key-pinning: 1.1.3 and react-native:0.68.7,react-native-cli in my project.
I added the below code in the login button action and checked the API call showing in the network inspector on the iPhone device.
I added the invalid public keys. I see the API call in the network inspector.
            await initializeSslPinning({
            'google.com': {
              includeSubdomains: true,
              publicKeyHashes: [
               'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
              ],
            },
          });

          axios.get('https://www.google.com').then((response)=>{
            alert(JSON.stringify(response))
        })
        .catch((error)=>{
            alert(error)
        })

![IMG_4086](https://github.com/user-attachments/assets/3075f3c7-ed6b-444e-b734-2b861959e7cb)

**Comment by frw** [comment]
Are you actually getting a successful response from the network call, or is an error generated?

You should see the call on Network Inspector since it should attempt to make the connection, but it shouldn't resolve if you've set up pinning with the dummy keys.

**Comment by gkasireddy202** [comment]
I got it. I will check with new public keys once I receive them from my admin team.

**Comment by frw** [comment]
Closing since this seems to have been resolved
