### ISSUE TITLE
Unable to use in Ionic React

### ISSUE THREAD

**Issue by manhtruongwang** [frw/react-native-ssl-public-key-pinning#366]
Is there anyway I can implement this in an Ionic React app? Installing via npm won't work without --legacy-peer-deps, and implement it via fetch will break the applications

**Comment by frw** [comment]
Hi @manhtruongwang

Unfortunately, this library only supports React Native. Ionic is an entirely different framework with its own ecosystem of libraries and packages. You will need to use an Ionic specific library to implement SSL pinning (e.g. https://ionic.io/docs/ssl-pinning).
