### ISSUE TITLE
SSL implementation issue

### ISSUE THREAD

**Issue by abhishekrup** [frw/react-native-ssl-public-key-pinning#38]
Hey, I am trying to do the setup on my react native project and i have added the domain and public hash keys but when i am adding wrong hash key then also it is working and in right hash key also it is working. Can you send me the solution so that i can implement because i want to write the code in javascript itself trying to ignore the native codes

**Comment by rikur** [comment]
Did you notice the additional notes at the end of the README?

https://github.com/frw/react-native-ssl-public-key-pinning#additional-notes

**Comment by frw** [comment]
@abhishekrup

Regarding requests succeeding when adding wrong key hashes, did you make sure to remove all key hashes and only provide the wrong ones? If at least one key hash matches any cert in your SSL cert chain, the request will succeed.

If you have indeed only provided the wrong key hashes, please provide the code that you've used and I can try and take a look at it.

**Comment by abhishekrup** [comment]
This is the code with wrong hashkey both the hash key's is wrong  but then also able to login 
useEffect(async () => {
    await initializeSslPinning({
      'clickit-eu-api.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'JKGH7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',
          'KH7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',
        ],
      },
      'clickit-eu-api-staging.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'TYS9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
          'UYtuyiS9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
        ],
      },
    });
  })
  
  This is the code with right hash keys 
  useEffect(async () => {
    await initializeSslPinning({
      'clickit-eu-api.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          '7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',
          '7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',
        ],
      },
      'clickit-eu-api-staging.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'S9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
          'S9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
        ],
      },
    });
  })
  
  I have added this code in my app.js file

**Comment by frw** [comment]
> 'JKGH7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',
> 'KH7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=er',

> 'TYS9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
> 'UYtuyiS9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',

I don't think these are valid SHA256 hashes. In fact, you should be getting a React Native warning regarding uncaught exceptions in your useEffect.
You need to use valid SHA256 hashes that don't match the certificates you are trying to pin. For example, you can use the placeholder SHA256 hashes I mentioned in the FAQ (https://github.com/frw/react-native-ssl-public-key-pinning#faq), as such:

```
useEffect(() => {
	initializeSslPinning({
		'clickit-eu-api.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
		'clickit-eu-api-staging.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
	});
}, []);
```

**Comment by abhishekrup** [comment]
Hii, The code which you have sent was working in ios properly but not working in android 
This is the code with wrong hash key 
useEffect(() => {
    initializeSslPinning({
      'clickit-eu-api.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
          'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAA=',
        ],
      },
      'clickit-eu-api-staging.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
          'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCC=',
        ],
      },
    });
  }, []);
  
  This is the code with right hash key 
 useEffect(() => {
    initializeSslPinning({
      'clickit-eu-api.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          '7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=',
          'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
        ],
      },
      'clickit-eu-api-staging.herokuapp.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'S9Pism00dGVw/CIRAZZnOJbumad1nBFZIuT4xYjakKI=',
          'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
        ],
      },
    });
  }, []);
  
  the same code is working in IOS when passing right hashkey then app working otherwise it is giving error but in android when passing wrong hashkey then also able to login and with the right haskkey then also able to login

**Comment by frw** [comment]
Your code for initialization seems right. Are you sure you've built the app with the library installed, and no other errors are happening when you are performing the initialization?
You can find out by adding a `catch` clause, like so:

```
useEffect(() => {
	initializeSslPinning({
		'clickit-eu-api.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
		'clickit-eu-api-staging.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
	}).catch((e) => console.error(e));
}, []);
```

If nothing is being logged to your console, it might be an issue with your code for fetching from the server. Please provide a minimal reproducible example that fails for you.

**Comment by abhishekrup** [comment]
Tried the above code of catch but not getting any console in catch 
useEffect(() => {
	initializeSslPinning({
		'clickit-eu-api.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
		'clickit-eu-api-staging.herokuapp.com': {
			includeSubdomains: true,
			publicKeyHashes: [
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
				'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
			],
		},
	}).catch((e) => console.error(e));
}, []);

If i add this code in my app.js so the app should not allow me to login in the app same is working for ios it got stuck on the otp screen but in android it move on also i had commented out the native code which i had implemented with the java code so can you help me out with any solution

**Comment by frw** [comment]
Closing as this doesn't seem to be a bug. Let me know if you have any additional issues.
