### ISSUE TITLE
In iOS SSL pinning is not working

### ISSUE THREAD

**Issue by imanshul** [frw/react-native-ssl-public-key-pinning#394]
I've tried and in iOS, whatever may be the key, the APIs always go through and never throws error. I've tested example app as well, on invalid scenario it always return success for fetch.

Please check.

<img src="https://github.com/user-attachments/assets/f5b8179c-dfe4-49cd-b11a-0c13e0aacc42" alt="Simulator Screenshot - iPhone 15 Pro - 2024-08-29 at 16 16 09" width="300" />

<img src="https://github.com/user-attachments/assets/6cd46748-2518-437c-9c53-278a94de94f6" alt="Simulator Screenshot - Android - 2024-08-29 at 16 14 09" width="300" />

**Comment by frw** [comment]
@imanshul Is this right after you launch the app, or did you successfully fetch first from the domain before attempting to pin?

Please see this note about iOS:
https://github.com/frw/react-native-ssl-public-key-pinning?tab=readme-ov-file#known-issues
> On iOS, SSL/TLS sessions are cached. If a connection to your site previously succeeded, setting a pinning configuration that should fail the following request would not actually fail it since the previous session is used. You will need to restart your app to clear out this cache.
