### ISSUE TITLE
Can I only use one public key to pin?

### ISSUE THREAD

**Issue by zhouhao27** [frw/react-native-ssl-public-key-pinning#395]
I got the following error:

> Failed to initialize SSL pinning [Error: TrustKit was initialized with less than 2 pins (ie. no backup pins) for domain xxx.xxx.com

How do I get the backup pins? Or if it's possible only to pin with one public pin? Thanks.

**Comment by frw** [comment]
Unfortunately, TrustKit (the iOS library we use to achieve pinning) requires at least 2 pins per domain: https://github.com/frw/react-native-ssl-public-key-pinning?tab=readme-ov-file#known-issues

You can generate a backup key using OpenSSL and extract the SHA256 hash of the public key, or you can use the public key hash of the intermediary cert or root CA as an alternative.

**Comment by zhouhao27** [comment]
> Unfortunately, TrustKit (the iOS library we use to achieve pinning) requires at least 2 pins per domain: https://github.com/frw/react-native-ssl-public-key-pinning?tab=readme-ov-file#known-issues
> 
> You can generate a backup key using OpenSSL and extract the SHA256 hash of the public key, or you can use the public key hash of the intermediary cert or root CA as an alternative.

Thanks for your reply. You mean I'm able to generate a backup key from current cert? Or I need another cert?

**Comment by frw** [comment]
You will need to have at least 2 distinct public keys, so extracting it from the same certificate will not work. What I suggested was to extract the public key from the intermediate CA cert or root CA cert which is part of the certificate chain of your original certificate (but this will mean you trust your CA to issue certs properly if you whitelist their public keys), or to generate a separate key pair entirely to use as your backup.

**Comment by zhouhao27** [comment]
> You will need to have at least 2 distinct public keys, so extracting it from the same certificate will not work. What I suggested was to extract the public key from the intermediate CA cert or root CA cert which is part of the certificate chain of your original certificate (but this will mean you trust your CA to issue certs properly if you whitelist their public keys), or to generate a separate key pair entirely to use as your backup.

I created another public key from root CA. Thanks.
