### ISSUE TITLE
Able to bypass SSLPinning on iOS using (objection - Runtime Mobile Exploration - https://github.com/sensepost/objection)

### ISSUE THREAD

**Issue by amanmoar277** [frw/react-native-ssl-public-key-pinning#439]
Able to bypass SSLPinning using (objection - Runtime Mobile Exploration - https://github.com/sensepost/objection) **on iOS**.

After using this, SSL Pinning is disabled easily on iOS. 

Is there any way to restrict this library from disabling SSL Pinning?

**Comment by pohtio6** [comment]
Hi, can you help me? I want to disable SSL pinning in an Java Android application, but I'm unsure how to do it

**Comment by amanmoar277** [comment]
Hey @frw, If you have any suggestions or thoughts on this, I'd really appreciate your input.

**Comment by amanmoar277** [comment]
> Hi, can you help me? I want to disable SSL pinning in an Java Android application, but I'm unsure how to do it

Hey @pohtio6, I have tried this on iOS application only. Could you please go through the steps mention here - https://github.com/sensepost/objection.

**Comment by frw** [comment]
Defeating SSL bypass techniques is not within the scope of this library. There is unfortunately no way to prevent it as there will always be a method to turn off SSL pinning if you are able to manipulate the memory of the application you are running.

Instead you should rely on other security measures like AppAttest and DeviceCheck to ensure the device/application has not been tampered with.

**Comment by amanmoar277** [comment]
Hi @pohtio6, are you able to disable SSL pinning on iOS?

**Comment by frw** [comment]
Closing since this is not something on the roadmap
