### ISSUE TITLE
For the Wrong Key also gets Success 200 - Android

### ISSUE THREAD

**Issue by chathuralakmal** [frw/react-native-ssl-public-key-pinning#45]
I have followed the instruction of installing the library. and in App.js i have added the following.

`  try {
    await initializeSslPinning({
      'google.com': {
        includeSubdomains: true,
        publicKeyHashes: [
          'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
          'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
        ],
      },
    })
      .then((response) => {
        console.log('THIS CALLED (1) ', response);
      })
      .catch((e) => {
        console.log('ERROR ####', e);
      });
  } catch (error) {
    console.log('ERROR ****', error);
  }

  // ...

  // This request should fail with an error
  try {
    const response = await fetch('https://google.com');
    console.log('RESPOSNSE (1) ----->  ', response.status);
  } catch (error) {
    console.log('ERROR ', error);
  }`

This always returns 200.

"react-native": "0.63.2",
 "react-native-ssl-public-key-pinning": "^1.0.6",

**Comment by frw** [comment]
Also, try change this line
```
const response = await fetch('google.com');
```
to this line
```
const response = await fetch('https://google.com');
```

**Comment by chathuralakmal** [comment]
@frw The example I downloaded it works fine. i cannot understand why it does not work in my app. could it be because of the react-native version?

**Comment by abhishekrup** [comment]
@chathuralakmal try running without debug you will get the correct response i think because i was also getting same issue but i disabled the debug and run then i am getting proper response

**Comment by chathuralakmal** [comment]
@abhishekrup @frw I Just found out it works fine in iOS. I believe may be its because it's using TrustKit. will try out trust kit android.

**Comment by frw** [comment]
Closing since the issue seems to be with an older RN version and workarounds have been provided.
Let me know if you're still facing any issues!
