### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by varunr107** [frw/react-native-ssl-public-key-pinning#6]
Hi ,

I have been trying to contact you regarding some of your work but I didn't manage to find any official way of contacting you. If possible please let me know any way to contact you.

**Comment by frw** [comment]
Hey @varunr107,

You can contact me through my LinkedIn: https://www.linkedin.com/in/frw/
Let me know if you need an alternative way of contact.

**Comment by varunr107** [comment]
Do you use any Instant Messaging apps ? That would be best

**Comment by frw** [comment]
You can contact me through Telegram: https://t.me/frederickwidjaja
