### ISSUE TITLE
SSL Pinning with Axios (expo)

### ISSUE THREAD

**Issue by LeoAnt02** [frw/react-native-ssl-public-key-pinning#75]
Hello

First of all, thank you for developing and maintaining the react-native-ssl-public-key-pinning library.

We are currently using Axios for making HTTP requests in our application, and we would like to apply SSL pinning to these requests using your library. 

We have noticed that the library's examples use the fetch API.

My Question: 
Can we apply the SSL pinning initialized by react-native-ssl-public-key-pinning to the HTTP requests made with Axios, and if so, could you provide us with an example of how this can be achieved?

Axios and fetch are different APIs that may not share the same underlying network transport, and there may be no guarantee that Axios will use the same networking stack that fetch (and presumably react-native-ssl-public-key-pinning) uses.

If Axios is not compatible with react-native-ssl-public-key-pinning, do you have any recommendations on how we can achieve SSL pinning with Axios?

**Comment by frw** [comment]
Hi @LeoAnt02,

Yes, this library will support axios. As mentioned in the [Overview](https://github.com/frw/react-native-ssl-public-key-pinning#overview) and [Additional Notes](https://github.com/frw/react-native-ssl-public-key-pinning#additional-notes), all network requests done through the standard React Native networking APIs (e.g. `fetch` and `XMLHTTPRequest`) will be covered by this library. axios uses `XMLHttpRequest` [under the hood](https://github.com/axios/axios/blob/21a5ad34c4a5956d81d338059ac0dd34a19ed094/lib/adapters/xhr.js#L72), and so will be affected by the pinning set by this library.

Let me know if you are having issues with integrating this library with axios.

Cheers.

**Comment by diegolmello** [comment]
This lib looks amazing.
Does it support WebSocket as well?
You've technically said it does, since it's on [Networking APIs](https://reactnative.dev/docs/network#websocket-support), but it doesn't hurt to ask :)
Thanks!
