### ISSUE TITLE
[Feature Request] Changing error text when request failed  SSL public key pinning failed

### ISSUE THREAD

**Issue by jakob-gh** [frw/react-native-ssl-public-key-pinning#95]
Hi, 

thank you for this great library!

When setting up the pinning and sending a request e.g. with axios there is no custom error message available to distinguish between normal network errors or SSL pinning related errors.

```
initializeSslPinning({
    'https://example.com': {
        includeSubdomains: true,
        publicKeyHashes: [
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
            'ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
        ],
    },
}).then(function() {

    axios.get('https://example.com').then(function() {

        console.log('success');

    }, function(err) {
        console.log('err:' + err.message);
    });

});
```

The **err.message** in this example always shows a generic 'Network Error'.

Would it be possible to add this to this library?

**Comment by frw** [comment]
Hey @ZMH3G,

I'm not sure returning something in the exception is possible. I believe modifying the exception returned by React Native's networking library would involve patching the React Native code, and probably not something I want to get into.

May I know your use case for this? What I could potentially do is to introduce a subscription which would emit an event if an SSL pinning error occured, or have a method to fetch whether the last request encountered an SSL pinning method. Would love to know first though how this would be useful to you.

**Comment by frw** [comment]
@ZMH3G 

This should be available now on v1.1.0 with `addSslPinningErrorListener`.

Checkout the example usage here:
https://github.com/frw/react-native-ssl-public-key-pinning#listener-example

Let me know if there are any issues with using it!

**Comment by frw** [comment]
> Amazing, thank you for the quick implementation!
> 
> I tried it on iOS , there it works.
> 
> On my Fire Tablet (based on Android 9) the SSL Pinning is working but the event is not emitted,
> i can try other android devices on monday if needed.

Interesting, what RN version are you using on Android?

**Comment by frw** [comment]
If you're still facing issues, do give v1.1.1 a try as well. It fixes an issue I found with earlier versions of RN (though RN v71 should not be affected), but it might just fix your problem as well.
